source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '10.0'

use_frameworks!
inhibit_all_warnings!

target 'refuge-ios' do
  pod 'ADClusterMapView', '1.1.0'
  pod 'AFNetworking', '~> 2.5'
  pod 'EAIntroView', '2.6.4'
  pod 'iRate', '~> 1.11'
  pod 'Mantle', '~> 1.5'
  pod 'Mixpanel', '~> 2.7'
  pod 'Reachability', '~> 3.2'
  pod 'HNKGooglePlacesAutocomplete', '~> 1.0'

  target 'refuge-iosTests' do
    inherit! :search_paths
  end
end
