language: objective-c
install:
  - brew remove --force xctool
  - brew install xctool --HEAD

script:
  - xctool test -workspace refuge-ios-v1/refuge-ios.xcworkspace -scheme refuge-ios -sdk iphonesimulator8.1
